### ISSUE TITLE
New user role management and welcome new users

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#1]
When a new user joins the server, they should automatically be given a role defined in the config.json. This role is meant to constrict what new users can do before agreeing to the T&C.

In the #terms-and-conditions channel, the user can react to a message to accept the T&C, which will result in the initial role being removed from them, followed by Horace announcing in the Citadel that a new user has joined the server.

**Comment by jenspetur94** [comment]
Hello ! 
I would like to work on this

**Comment by Moesgaarda** [comment]
@jenspetur94 How is this issue going?

**Comment by Moesgaarda** [comment]
Solved in #42
