### ISSUE TITLE
Horace translation feature

### ISSUE THREAD

**Issue by Dendrobyte** [Knights-Of-Academia/horace#106]
**Is your feature request related to a problem? Please describe.**
Nope! It might be cool to have a translation feature to help with communication.

**Describe the solution you'd like**
Hooking into the Google Translate API to translate words or phrases with `!translate <phrase/last> <from language> <to language> [phrase]`, such as `!translate phrase english french Welcome to KOA!` or `!translate last english italian` which translates the last sent message.

**Describe alternatives you've considered**
As i write the above I realize the command gets kinda convoluted and this is more just of a fun gimmick than anything

**Additional context**
Nada :)

**Comment by ghost** [comment]
https://www.npmjs.com/package/translate This might be useful for this! Maybe I could take this up, let me finish up what I need to do for school and the !help changes....

**Comment by Dendrobyte** [comment]
Ye no worries! Was a cool thought I had from a discussion w/ Rani in
compsci channel if you wanna check that out. I gotta finish what I've
currently assigned myself to so... 😂

On a sidenote, i should have some time to check out your unit test tonight
👌

**Comment by ghost** [comment]
The guild command got transferred to another persons project, but it still might be helpful to know what i did wrong if you can figure it out!

Checking out compsci channel now!

**Comment by debashisbiswas** [comment]
I'll take this one!
