### ISSUE TITLE
Facebook command

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#11]
The command !facebook (alias !fb) should return a link to the KOA Facebook page.

**Comment by Manon-B** [comment]
ExtraCognition here :)
I'd like to try to do this if that's ok. 
I just have one question : the KOA Facebook page is the _KOA Foundation_ group, right ?

**Comment by Dendrobyte** [comment]
> 
> 
> ExtraCognition here :)
> I'd like to try to do this if that's ok.
> I just have one question : the KOA Facebook page is the _KOA Foundation_ group, right ?

Yep! Here's a direct link just in case: <https://www.facebook.com/groups/1895927804047033/>
