### ISSUE TITLE
Recognize "goodnight" as well as "good night"

### ISSUE THREAD

**Issue by Dendrobyte** [Knights-Of-Academia/horace#111]
When someone says "good night", horace properly reacts with a moon. However, "goodnight" does not trigger the same thing.

See pull request #69 for the proper class to edit.

**Comment by ghost** [comment]
Do we know why goodmorning/night are in both greetingActions.js and citadelActions.js? Don't they have the same range? 

Added edit: greetingActions.js literally has `if (config.channels.citadel) {` in it...I think this might need some cleanup LOL

**Comment by ghost** [comment]
Gonna unassign this and let someone else take this on, I tried adjusting the expression it recognizes but I don't now Regex well enough 😆

**Comment by debashisbiswas** [comment]
Mind if I take this one?

**Comment by ghost** [comment]
@debashisbiswas Feel free!

**Comment by debashisbiswas** [comment]
@cosmiccdev Did you ever figure out why goodmorning/night are in both greetingActions.js and citadelActions.js?

It seems that the citadelActions is never used - the one that ends up handling the reactions is that one in greetingActions.js

**Comment by debashisbiswas** [comment]
Figured it out, it was related to merge conflict cc25ace1c47532680488d055bd9c7eae6b3f4c7c right after PR #69 
It seems that citadelActions.js is more descriptive of the functionality, and would be better to keep for further actions that may be added. I'll plan on keeping citadelActions in my changes
