### ISSUE TITLE
[BUG REPORT] Good Morning/Night Reactions acting Weird

### ISSUE THREAD

**Issue by ghost** [Knights-Of-Academia/horace#119]
**Please Describe Your Issue**
According to Alex, good morning/night emoji reacts are being added to the responses rather than the initial message containing the phrase.

**How to Reproduce**
Send "good morning" or "good night" and have someone send a message either.

**Expected behavior**
Emoji react is supposed to go to the earlier message.

**Discord Information**
 Not Discord client related.

**Extra Context**
![image](https://user-images.githubusercontent.com/16247799/72307777-0e5d6f80-3641-11ea-8cc2-91082b49628a.png)

**Comment by Tekrus** [comment]
Not a bug, a misunderstanding of how the feature actually works
