### ISSUE TITLE
Choose command

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#12]
The !choose command (alias !pick) should take a list of options as input and return on of them at random.

Eg: "!choose go to sleep, eat more, programming" should return either "go to sleep", "eat more" or "programming" to the user.

**Comment by ziebam** [comment]
Time to try my hand at a slightly harder issue. I'll pick this up if that's okay!

**Comment by Dendrobyte** [comment]
> 
> 
> Time to try my hand at a slightly harder issue. I'll pick this up if that's okay!

I believe in you! Thank you for helping us out
