### ISSUE TITLE
Condense accountability unpin

### ISSUE THREAD

**Issue by ghost** [Knights-Of-Academia/horace#138]
Currently if a user unpins multiple messages, Horace sends a message for every one. 

https://bit.ly/33JuZXK

Solution: if a user unpins multiple messages, the Horace message should be edited to say "Hey, [user], I've unpinned your [#] most recent messages as requested!"

**Comment by Dendrobyte** [comment]
Huh, not sure how I missed out on that use case! haha. I'll work on that at some point as well, but can't promise tonight. Perhaps end of the upcoming week

**Comment by catalincodes** [comment]
Hey @KO4JZT @Dendrobyte 

Just wanted to verify if anyone is working on this issue. Otherwise, given I'm familiar with the accountability command I could look into this.

Thanks, 
Catalin

**Comment by Dendrobyte** [comment]
> 
> 
> Hey @KO4JZT @Dendrobyte
> 
> Just wanted to verify if anyone is working on this issue. Otherwise, given I'm familiar with the accountability command I could look into this.
> 
> Thanks,
> Catalin

I guess that "end of week" never hit 😅 All yours!

**Comment by catalincodes** [comment]
This has the tag #hacktoberfest would we call this a "feature" or a "bug"? 
I say it's a "feature". It's not that something is broken.

@debashisbiswas Thoughts?

**Comment by debashisbiswas** [comment]
'Enhancement' should be the most accurate description here!

**Comment by debashisbiswas** [comment]
Decided to drop this issue in favor of maintaining the channel history (see #254 and #269)
