### ISSUE TITLE
Goodreads command

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#14]
The command !goodreads (alias !gr) should return a link to the KOA good reads page.

**Comment by jenspetur94** [comment]
hello ! 
I would like to work on this issue if possible :)

**Comment by Moesgaarda** [comment]
Sure, have fun with it! 🚀

**Comment by Moesgaarda** [comment]
Yes @LemonHex - that would be awesome! Thanks for helping us out

**Comment by Moesgaarda** [comment]
Hi @LemonHex - any progress on this issue? 👋

**Comment by LemonHex** [comment]
Hi, really sorry for my inactivity. Have been out of town without a PC, I can get this issue done once I get back or if it’s more convenient for you, feel free to assign it to someone else. Again my apologies 😊

**Comment by Moesgaarda** [comment]
@LemonHex No problem, you can re-assign yourself if you decide to come back to work on it 😄

**Comment by jenspetur94** [comment]
I would like to work on this if possible :)
