### ISSUE TITLE
Move the Profanity Filter to a Database

### ISSUE THREAD

**Issue by RaniOfTheRain** [Knights-Of-Academia/horace#149]
I thought it might be worth moving this feature to a database as well so that we're able to add and remove terms as necessary.

This would require creating a command like !profanity add/remove to allow for edits within the server.

**Comment by RaniOfTheRain** [comment]
I don't know how to remove the bug label as it really isn't a bug

**Comment by ghost** [comment]
Sure, this sounds interesting!

**Comment by Dendrobyte** [comment]
Send it! ⚔️

**Comment by ghost** [comment]
Reopening this as I just realized that #173 doesn't add in a case for the program being helpers or guardians only. If this could be added as well that would be great, I can also just knock it out very quickly tomorrow
