### ISSUE TITLE
AFK feature

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#15]
A user should be able to set an AFK message eg:
"!afk Out on a walk, DM if important" 

If a user is tagged in a channel while marked as AFK, Horace should post their AFK message.

If the user posts a message while AFK, they should be prompted by the bot if they want to remove their AFK status (should be confirmed by reacting to the bots message either a confirm (check mark) or deny (cross) emoji.

It would be preferable that the bot automatically reacts to its "remove afk" confirmation message with the two emojis, so the user will only have to click one of them to confirm.

After a user reacts to a confirmation message, the message from the bot should be removed.

Example from the previous version:
![image](https://user-images.githubusercontent.com/21969475/67544660-a741b600-f6f6-11e9-9e7a-f4fd20b16e12.png)

![image](https://user-images.githubusercontent.com/21969475/67544637-92652280-f6f6-11e9-9702-b59e67419d40.png)

**Comment by Zaph-x** [comment]
If this issue has not been picked up by anyone, I would like to claim it and make it

**Comment by Tekrus** [comment]
@Zaph-x Feel free to! Make sure to hit up @Dendrobyte before starting, he's working on integrating a SQLite database, which will make this issue a bunch easier.

**Comment by Zaph-x** [comment]
I talked to Mark and he mentioned I would be able to fork a version with the database, some time tomorrow.

**Comment by Zaph-x** [comment]
Update on this: I have started work and I am able to successfully mark someone as AFK, as well as remove that status.

I can see I have not been assigned to this issue yet. Is that a possible?
