### ISSUE TITLE
[REQ] Time zone conversion

### ISSUE THREAD

**Issue by debashisbiswas** [Knights-Of-Academia/horace#150]
**Is your feature request related to a problem? Please describe.**
Not necessarily, but this could improve quality of life. KOA members are all over the world, and sometimes it can be difficult to figure out times when everyone is in a different time zone.

**Describe the solution you'd like**
Horace could have a command that helps user convert between time zones. The command could get complicated, so this might not be ideal, but it definitely could be helpful!

**Describe alternatives you've considered**
Horace could alternatively link you to a website that can convert between different time zones.

**Comment by pralkarz** [comment]
I can pick this one up.
