### ISSUE TITLE
[REQ] Cooldown delay between AFK prompts

### ISSUE THREAD

**Issue by zmontgo** [Knights-Of-Academia/horace#163]
Whenever you send a message Horace prompts you to turn off AFK and it easily gets spamming. I propose we add a 3-minute delay between each ability to prompt so that people can say one or two more things before they leave, or if they pop in real fast in the middle of doing something. (Say, they're working and need to update someone on how they're doing or whatnot)

**Comment by pralkarz** [comment]
I can pick this up.

**Comment by ghost** [comment]
Zach actually has an open PR for this #164 that I just haven't gotten around to closing. @ziebam
