### ISSUE TITLE
[REQ] Horace reacts to "I am grateful for" in the gratitude channel"

### ISSUE THREAD

**Issue by Dendrobyte** [Knights-Of-Academia/horace#165]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/12663558/85958159-50fdd480-b961-11ea-868b-249032844bff.png)

**Additional context**
What channel this reaction occurs in should be configurable in the `config` such that we can set it to the gratitude channel. The regex should detect `today i am grateful for` (case insensitive)

**Comment by pralkarz** [comment]
It's me again and I would like to pick this up! ^^

**Comment by Dendrobyte** [comment]
Great! Go for it :D
