### ISSUE TITLE
[REQ] !firstweek command

### ISSUE THREAD

**Issue by pralkarz** [Knights-Of-Academia/horace#180]
As per the request from the #citadel channel in the Discord. A simple command (similar to `!website` for example) that would make Horace fetch the link to "Your First Week at KOA" guide. It could be a good first issue for Hacktoberfest folks!

![image](https://user-images.githubusercontent.com/31964869/93013827-34f6f000-f5ac-11ea-9229-5d2771053aa1.png)

**Comment by lieuweberg** [comment]
Can I pick this up?

**Comment by ghost** [comment]
@lieuweberg Sure! For the link, use https://koa.gg/firstweek :D

**Comment by lieuweberg** [comment]
koa.gg/firstweek is not loading for me at all or very slowly, but the https://knightsofacademia.org/your-first-week-at-koa/ site works fine. Should I just use that instead?

**Comment by ghost** [comment]
@lieuweberg I need to create the link. It should work in just one second.

**Comment by ghost** [comment]
Should work now.
