### ISSUE TITLE
[REQ] Documentation Channel

### ISSUE THREAD

**Issue by zmontgo** [Knights-Of-Academia/horace#207]
**Is your feature request related to a problem? Please describe.**
Many features of Horace are commands, but many are not. It may be helpful to let members know about Horace’s non-command features (as well as some command features that may not be clear from help), like reactions, message chains, AFK, and upcoming scoreboard.

**Describe the solution you'd like**
I think the best and cleanest way would be to create a channel towards the bottom of KOA that lays out some of the less clear things.

**Describe alternatives you've considered**
Could create a big message embed with `!info` command that details it all, but that may be messy.

**Additional context**
I did this for Finriq and am updating it with new features to help members know about new changes, commands that aren’t clear, non-command features, etc. Also I laid out how to contribute to Finriq in a message about it asking for people to submit an issue on github, so that may be a good place to do the same.

**Comment by ghost** [comment]
Few ways to do this that I think could be interesting to try and crack.

1. Documentation webpage that is sent alongside !help or in its own command. 
2. Documentation channel on the Discord server.
3. Better layed out !help command.

**Comment by ghost** [comment]
Whoops! Didn't mean to close this - hit `close with comment` instead of `comment`.
