### ISSUE TITLE
Add !article command

### ISSUE THREAD

**Issue by debashisbiswas** [Knights-Of-Academia/horace#218]
Add an `!article` command. When a user uses the `!article` command, Horace should respond with a link to the most recent KOA article.
Specific copy for this command is pending, but can be finalized once someone is assigned to the issue.

**Comment by mukkuzzz** [comment]
I can do that

**Comment by debashisbiswas** [comment]
@mukkuzzz We've gotten an update on how this command should be structured.

`!article` - link to a random article
`!article home` - link to webpage with all articles
`!article latest` - link to the latest article

For handling arguments, check out the `!invite` command. For getting the episodes, you can use RSS similar to the `!newsletter` command.

**Comment by mukkuzzz** [comment]
@debashisbiswas i have implemented those arguments u can review the PR
