### ISSUE TITLE
Remind new users to accept Terms and Conditions after specified amount of time

### ISSUE THREAD

**Issue by debashisbiswas** [Knights-Of-Academia/horace#220]
This proposed change handles the case in which a new user joins KOA but does not accept the Terms and Conditions (TOC).
When a user joins KOA and has still not accepted the TOC after a certain (configurable) amount of time, Horace should send them a DM reminding them to accept the TOC.

The DM should be an embed, with this content: (replace #terms-and-conditions with a direct link to the channel)
```
Hey :wave: noticed you joined, but never got access to KOA. 

Tap the check mark in #terms-and-conditions to have full access to all KOA channels. Enjoy your newfound powers :relieved:
```

**Comment by mukkuzzz** [comment]
I think i am interested but how do u think this can be accomplished? @debashisbiswas

**Comment by debashisbiswas** [comment]
@mukkuzzz This isn't an exhaustive solution, but maybe something like this:

When a user joins the server, add a row to the database that stores information such as their id and join time.

When they accept the ToC, update the database entry to reflect that they're 'accounted for'. This could be a flag, or we could just delete them from the database.

Perodically run a function that checks the status of the database. In this function, send the DM to every user in the database that has joined but not accepted the ToC in the configured amount of time. Then mark as those users 'accounted for' as mentioned above, so that they don't get the DM multiple times.

**Comment by ThatNerdSquared** [comment]
This could work similar to how reminders currently work as well, I'm not 100% sure how you would go about this issue but I'd check out how the remind commands work as a start.

**Comment by mukkuzzz** [comment]
Thanks let me take a look at the reminder command
