### ISSUE TITLE
[BUG REPORT] Highlights trigger when matched phrase is inside part of a word

### ISSUE THREAD

**Issue by ThatNerdSquared** [Knights-Of-Academia/horace#249]
**Please Describe Your Issue**
When a user has something highlighted (e.g. `test`), Horace DMs them when a message has another word that has that phrase (e.g. `tested`).

**How to Reproduce**

*Note: Please do not try to replicate with these test words, or in KOA itself, as that spams users that have these terms highlighted.*

1. Highlight phrase
2. Have another user send a message with that phrase, inside another word (e.g. highlight `Sam` and send `Same`).
![image](https://user-images.githubusercontent.com/72814106/119281929-7c7a5500-bbec-11eb-8afc-b642bc3a717b.png)

**Expected behavior**
Horace should only alert user when the phrase they've highlighted appears on its own.

**Extra Context**
Probably just need to adjust a regex or two, to make sure there's only spaces or punctuation on either side of the highlighted phrase.

**Comment by mukkuzzz** [comment]
@ThatNerdSquared, plus there is also an issue where even when i tried to add the word sam to my highlights it shows that it already exists.

**Comment by debashisbiswas** [comment]
@ThatNerdSquared Did PR #274 fix this issue? Confirming before closing

**Comment by ThatNerdSquared** [comment]
Yes, it did!
