### ISSUE TITLE
Emoji reactions in accountability station

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#26]
**Is your feature request related to a problem? Please describe.**
When people write a message in #accountability-station, he no longer reacts with a random encouraging emoji, I'd love for this feature to return!

**Describe the solution you'd like**
I want Horace to react with emojis to all tasks containing a sort of checkmark in the accountability channel, to help encourage people to finish more tasks.

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by Dendrobyte** [comment]
Will tackle this one next, but if anyone gets to it before me, some ideas:
✅ or :yes2: if it contains one of the checkmark effects
💯 👍 🔥 and 2 or 3 others selected at random for completed tasks
🎏 Corresponding flags if a language is mentioned, common ones are french, spanish, italian (from what I've seen)
🍅 If it contains 'pom'

**Comment by Dendrobyte** [comment]
Forgot this was a separate issue- just wanted to confirm that I'm on it!
:rocket:

**Comment by Dendrobyte** [comment]
More recs on random reacts:

🙌 👏 👌 💪 :1000: :muscle_reverse: :LETSGO:
