### ISSUE TITLE
Manage Champion of the Week role position

### ISSUE THREAD

**Issue by debashisbiswas** [Knights-Of-Academia/horace#265]
Whenever a user wins the Challenge of the Week, they are given a role (Champion of the Week) until the end of the next challenge. This role changes the user's name color to red, but does not give them extra permissions - it is purely cosmetic. Currently, this is done manually: whenever a new Champion is selected, the role is moved just above the user's highest role (this gives them the color, but no extra permissions), and moved again whenever the current Champion changes. This should be automated.

**Comment by cjtheham** [comment]
Closed in PR #295
