### ISSUE TITLE
[REQ] Add reaction in gratefulness club

### ISSUE THREAD

**Issue by ThatNerdSquared** [Knights-Of-Academia/horace#271]
Whenever somebody begins a message with "Today I am grateful for" in the #gratefulness-club channel, a :relaxed: reaction should be added to the message. Requested by Ankle#2072.

**Comment by debashisbiswas** [comment]
This should already be implemented here:
https://github.com/knights-of-academia/horace/blob/develop/eventActions/gratitudeActions.js
Not sure why it's not showing up in production though. Config variables seem to be set properly, and it works in local tests

**Comment by debashisbiswas** [comment]
See issue #277 
The gratitude reaction is handled after highlight messages, so when highlight messages throws an error, we're out of the function before getting to the gratitude reaction.
