### ISSUE TITLE
[REQ] Reinstate the !raid command

### ISSUE THREAD

**Issue by ThatNerdSquared** [Knights-Of-Academia/horace#272]
Currently the !raid command is nonexistent after a shift in KOA's raid room setup. It should be brought back with a message that looks like:

> **RAAAAAAAAAAAAAAAAAAAID** :crossed_swords: with [ping user here]
> Join the raid at #raid-room

Requested by @MrFrizzyBottom.

**Comment by debashisbiswas** [comment]
Dropping; will include this in the requirements for the shared timer addition.
