### ISSUE TITLE
Bookmark Feature

### ISSUE THREAD

**Issue by LemonHex** [Knights-Of-Academia/horace#29]
react to message with 🔖 for Horace to "bookmark" that message by sending it and pinning it in your direct messages. 
direct message includes channel, author, message, link to message that redirects you to given message as well as date message was sent.  
example image below: 

![image](https://user-images.githubusercontent.com/47442751/66582989-d75a5800-eb3f-11e9-905b-c58fbb7e01ae.png)

**Comment by ziebam** [comment]
I'd like to pick this up as well if that's not too much to ask for. Would start working on it after my current PR gets merged.

Gotta push my limits to learn as much as possible! :D

**Comment by Dendrobyte** [comment]
Full send! Here's to more learning and thanks for contributing! 💻

**Comment by cosmiccdev** [comment]
It doesn't look like ziebam is working on this anymore, mind if I take it up?

**Comment by cosmiccdev** [comment]
Finished with #98! Can be closed now.
