### ISSUE TITLE
Repetitive Reminders (Deprecate ReminderBot)

### ISSUE THREAD

**Issue by Burndown9** [knights-of-academia/horace#30]
Many newcomers express interest in daily reminders, but the Reminder bot doesn't allow for new people to set reminders for themselves in #accountability-station anymore. Horace should take up that role, and allow people to set repetitive reminders for themselves using some kind of command.

**Comment by pralkarz** [comment]
This one seems like a decent challenge. Can I pick it up? ^^

**Comment by ghost** [comment]
Sure!
