### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by ziebam** [Knights-Of-Academia/horace#32]
**Is your feature request related to a problem? Please describe.**
There isn't a way for a regular user to see a list of possible Horace commands.

**Describe the solution you'd like**
A simple `!help` command will probably suffice, as long as it's regularly updated. Maybe some optional args like `dm` in the Pomodoro bot.

**Comment by Dendrobyte** [comment]
Is it possible to give command js files description "attributes" (so to speak)? 

In that event, we could even make this dynamic before we have too many commands to update by listing all files that are command handlers.

Just throwing it out there as an idea

**Comment by Zaph-x** [comment]
Assuming this is open to anyone, I would love to take an attempt at adding this feature.
