### ISSUE TITLE
Good morning or night greetings

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#36]
**Is your feature request related to a problem? Please describe.**
People love it when the bot greets them when they say good morning or goodnight, we should include a feature where the bot does so!

**Describe the solution you'd like**
When a message contains morning related keywords (good and morning in the sentence) or 
night related keywords (good and night in the sentence) should be reacted to with either a sun or a moon emoji.

**Additional context**
This feature should only work in the citadel channel.

**Comment by Zaph-x** [comment]
Is it a requirement that the message includes at the end or would "good morning" and "good night" suffice?
