### ISSUE TITLE
Focused Raider Feature

### ISSUE THREAD

**Issue by suchafunnyunicorn** [Knights-Of-Academia/horace#40]
The Focused Raider role used to block all the channels except accountability station i think and choose your roles. I might be missing some information here but ithe feature is needed :D 

**Is your feature request related to a problem? Please describe.**
People get distracted when they open discord to raid so focused raider helps to block out all the channels except accountability station and choose your roles (i think it was just these two channels  I'll ask and let you know) so it minimises distraction.

**Describe the solution you'd like**
The ability to react to the :letsgo: emoji in the choose your roles channel so that one can enter focused raider and work peacefully.

**Describe alternatives you've considered**
I haven't thought of any alternatives to this yet. Sorry!

**Additional context**
Go ahead and provide us with additional context, or even screenshots, of what this might look like! For example, you type a command and a friend pretends to be the bot! :)

**Comment by Moesgaarda** [comment]
Hi!
Please use the feature request template when requesting a feature, it should be automatically filled in when you created the request.

`**Is your feature request related to a problem? Please describe.**
Is there an issue with Horace that your feature will solve? Ex. I'm always frustrated when [...] so to fix that Horace should [...]

**Describe the solution you'd like**
Let us know what the solution is, and how it would solve this for you. If it's a feature not related to an issue, describe it to us.

**Describe alternatives you've considered**
Are there any other solutions or components to this feature that you have considered?

**Additional context**
Go ahead and provide us with additional context, or even screenshots, of what this might look like! For example, you type a command and a friend pretends to be the bot! :)`

**Comment by Dendrobyte** [comment]
Looking to get accountability emojis done at the end of the week, and I'd like to jump on this one next! 

Will be fun to dive into rank editing- if anyone does come along and I haven't left other comments, don't hesitate to work on it also
