### ISSUE TITLE
Chain messages

### ISSUE THREAD

**Issue by suchafunnyunicorn** [Knights-Of-Academia/horace#44]
**Is your feature request related to a problem? Please describe.**
This request isn't related to a problem per se. It was like an easter egg. Whenever a few of us sent the same message anywhere as a chain Horace used to send one too and it was the cutest and most awesome thing. So we would like that feature added please. It's not fun to chain without Horace.

**Describe the solution you'd like**
A automatic inbuilt command which makes Horace send the same chain message as everyone else.

**Describe alternatives you've considered**
There can be NO alternatives to Horace's chain messages. None whatsoever.

**Additional context**
I'll back to you with a screenshot.

**Comment by Dendrobyte** [comment]
General question- is this only enabled in a specific channel/some specific channels? or is it everywhere

**Comment by Moesgaarda** [comment]
I'm pretty sure it used to be enabled everywhere

**Comment by Tekrus** [comment]
Closed in #110
