### ISSUE TITLE
User controlled pinning

### ISSUE THREAD

**Issue by grktarik** [Knights-Of-Academia/horace#45]
**Is your feature request related to a problem? Please describe.**
I am Always frustrated when we need to wait for someone with a pinging role to ping stuff

**Describe the solution you'd like**
WE should try having a Limit with react till pin number. It will be ofc different for each channel 

**Describe alternatives you've considered**
You could make Tek stand front of PC and wait someone to request a pin 24/7...

**Additional context**

Typing on Mobile is hard

**Comment by Dendrobyte** [comment]
Heya! I assume this relates to all the pings in #accountability-station, and I just wanted to let you know this is related to #7 and #43 and I wanted to let you know I'll be working on that feature throughout the week! If you were thinking something more specific, definitely let me know!

**Comment by grktarik** [comment]
Hey Me being so sleepy last night forgot to add some (crucial) details here. What I was thinking was for example in BOTM channel if X amount of people react with pin message it would ping that message.

 This can be useful when we post pdf's of book in BOTM. A resource on COTW, Or maybe smthn for Discussion wing channels.

**Comment by Dendrobyte** [comment]
Resolved by #60
