### ISSUE TITLE
List of commands available in info

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#54]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to see which info search terms are available.

**Describe the solution you'd like**
!info should return a list of search terms

**Describe alternatives you've considered**
We could have a list on the website?

**Additional context**

**Comment by debashisbiswas** [comment]
Would it be alright if I took this one?

**Comment by Moesgaarda** [comment]
Sure, we'd appreciate it @debashisbiswas 🚀

**Comment by debashisbiswas** [comment]
Glad I could help :) should be able to close this one now, sorry for not putting the right words in the PR to do that automatically!
