### ISSUE TITLE
Resource Library

### ISSUE THREAD

**Issue by erik-schmidt** [knights-of-academia/horace#59]
**Is your feature request related to a problem? Please describe.**
The resouce-library gets flooded with resources and it's hard to search through them eventhough we have tags in them.  

**Describe the solution you'd like**
It would make it much easier if we would have a third-party service (i.e. Google Sheets) to save the articles there and quickly search thorugh them. We could write in a template, like we have right now and the bot would save them in a google sheets and remove the post afterwards.

**Describe alternatives you've considered**
Other services. (Needs research).

**Comment by Moesgaarda** [comment]
We're working on implementing a resource library on the website - marking this feature request as blocked until the website feature is online. ⚔️

**Comment by ghost** [comment]
- [ ] Integrated Sector Libraries in Discord
- [ ] Website Resource Library and Discord Link
