### ISSUE TITLE
ONGOING THREAD: Info Messages

### ISSUE THREAD

**Issue by grktarik** [knights-of-academia/horace#66]
This thread is created for Helping Our beloved Horace to get over his Amnesia and Remember Our Info messages.

Just like Amnesia If we tell him he will remember it.
Let's go hunting Info Messages.

**Comment by Moesgaarda** [comment]
I'd like info on the following:

- Notion
- Some users (just for fun)
- Pom war
- Donation to KOA

**Comment by Dendrobyte** [comment]
Some other ideas (ranks)

- !sectorleader/!sectorhand
- !page/!squire/ranks you can get by levels

**Comment by grktarik** [comment]
I say we always use the "!info X" style cuz we will have commands like !info raid and it shouldn't interfere with other commands.


 For Level ranks we could just.... Copy paste The Map of KOA

**Comment by Dendrobyte** [comment]
Oh shucks, I meant those as in being terms added on to !info, my bad haha.
Also yea, fair point on a simple redirect to the map :P

**Comment by grktarik** [comment]
I have added (yea added. This still sounds weird) the info for Xp roles.

**Comment by disturbedmanYT** [comment]
URGENT

!info disturbedman

should print one of the following (you choose!):

"A master economist, and maybe tennis player? 🤔" 
"Economics and the most exciting love life you've ever seen, what else does a man need?"

**Comment by Dendrobyte** [comment]
![image](https://user-images.githubusercontent.com/12663558/69503980-f85aea80-0eec-11ea-8d98-5116e44ddfdc.png)
Updated! I'll make a PR in just a moment.

**Comment by RaniOfTheRain** [comment]
I made a PR for some updated Info commands based on this thread. In particular Role Infos. (Sorry I didn't link the PR, still new to Git(Hub/Lab)

**Comment by ghost** [comment]
Best spot for info messages will be #the-idea-dome with a coming update, this thread is now deprecated.
