### ISSUE TITLE
Pinning and unpinning messages based on reaction

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#7]
If the author of a message reacts to their own message in #The-Accountability-Club with the push-pin emoji it should be pinned.

If they remove the reaction, the message should be unpinned.

**Comment by Dendrobyte** [comment]
I'll get this one! I use #accountability-station a lot and would love to tackle this :) Blocking out time this week to learn this stuff and on Monday will get around to this. Logistically doesn't seem like too much... 😅

**Comment by Dendrobyte** [comment]
Quick note for feature:
- A reminder when a list has been pinned for more than a week, i.e. "How's your progress on your pin from x/x/x? Shall I unpin it?"
