### ISSUE TITLE
Horace sends a double confirmation when pinning pinning

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#72]
**Please Describe Your Issue**
When something is pinned in accountability station, Horace will post a message - plus discord will inform about it.
Only one is needed.

**How to Reproduce**
1. Pin something
2. See two messages with same information

**Expected behavior**
Only discord should be shown

**Extra Context**

![image](https://user-images.githubusercontent.com/21969475/67519290-d4667800-f6a6-11e9-92c5-0dc67d987b7b.png)

**Comment by Dendrobyte** [comment]
I'll fix this one w/ the emojis for this weekend :D

**Comment by Dendrobyte** [comment]
Also appears that Horace won't recognize past messages as pinned, despite presence in the pinned list. I know what I'm doing on Saturday! 
![image](https://user-images.githubusercontent.com/12663558/67569571-3c47ad80-f6fd-11e9-9b2b-cecc7e884d1d.png)
