### ISSUE TITLE
Horace should confirm COTW events

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#73]
**Is your feature request related to a problem? Please describe.**
When Horace does something related to COTW management, he should give a confirmation to the COTW manager to let them know that it was successful.

**Describe the solution you'd like**
React to their message with checkmark when a poll is posted, shield when a challenge is posted and 🎉 when a new champion is selected.

**Describe alternatives you've considered**
Can send a message in the channel to confirm.

**Comment by Tekrus** [comment]
Solved in #96
