### ISSUE TITLE
Removing a RichEmbed message throws an empty field exception

### ISSUE THREAD

**Issue by Moesgaarda** [Knights-Of-Academia/horace#77]
**Please Describe Your Issue**
If you remove a message with no text other than a rich embed (For example a profanity warning in moderation) the following exception is thrown:
 UnhandledPromiseRejectionWarning: RangeError: RichEmbed field values may not be empty.

**How to Reproduce**
Please tell us how this error came about.
1. Delete a message to trigger deletion moderation
2. Go to moderation channel and see that the message was deleted
3. Delete the confirmation message
4. ERROR

**Expected behavior**
Horace should either not try to repost deleted messages from bots, or at least not throw an error.

**Comment by jenspetur94** [comment]
i would like to work on this
