### ISSUE TITLE
Sleep Reactions do not occur on all instances of "Sleep Log"

### ISSUE THREAD

**Issue by steventnorris** [Knights-Of-Academia/horace#80]
**Please Describe Your Issue**
It has been noted by kugoi and wordvalkyrie that the sleep reaction is not occurring for all instances of "Sleep Log". It's possible this is due to some sort of formatting issue. I know wordvalkyrie had theirs underlined. We may just need to add some extra checks here for what triggers the reaction.

**How to Reproduce**
Please tell us how this error came about.
1. Post a "Sleep Log" (in particular underlined, but noted that various forms are not triggerring) in the early-to-sleep channel.

**Expected behavior**
Bed reaction

**Discord Information**
 - Are you updated to the most recent version of Discord?
Yes
 - Are you on mobile or browser?
Both

**Smartphone (please complete the following information):**
Unsure

**Extra Context**
Submitting this on behalf of kugoi and wordvalkyrie who do not have git accounts currently

**Comment by Moesgaarda** [comment]
This was not really a code issue, it was due to an update in the config file that set an incorrect emoji as reaction.
