### ISSUE TITLE
Assign Champion role when congratulated in COTW

### ISSUE THREAD

**Issue by steventnorris** [Knights-Of-Academia/horace#81]
**Is your feature request related to a problem? Please describe.**
Switching the champion role for COTW was once automated based on a congratulations message by the leader of the COTW channel.

**Describe the solution you'd like**
If COTW leader (possible just role based in case someone is filling in for COTW) says "Congratulations @soandso" Horace would remove current champion and give the new person the role. He would also move the position of champion if needed so it would be above any other roles the person had, or move it back to it's normal position if it had been moved previously.

**Describe alternatives you've considered**
Currently doing this manually. Some sort of automation or easy way to swap the role to a new person would be helpful

**Additional context**
Submitting on behalf of kugoi, who does not currently have a git account.

**Comment by Moesgaarda** [comment]
This is already implemented and should work if the COTW role says "congratulations @user" in the channel.
