### ISSUE TITLE
Horace does not inform if a channel has reached max pins

### ISSUE THREAD

**Issue by Dendrobyte** [Knights-Of-Academia/horace#89]
**Please Describe Your Issue**
When a channel has reached the maximum pins, Horace throws an error in console instead of posting a message and then not trying to pin.

**How to Reproduce**
1. Pin 50 messages
2. Try to pin another one

**Expected behavior**
Horace should inform the channel that it has reached the max pins

**Comment by Tekrus** [comment]
Solved by #95
