### ISSUE TITLE
Starboard

### ISSUE THREAD

**Issue by KO4JZT** [knights-of-academia/horace#92]
**Describe the solution you'd like**
Similar to the Starboard Discord bot, this feature would allow for messages getting a certain amount of reactions to be placed in a separate channel, to be archived and shown to others as a way to show off things like cool artwork, interesting resources, or anything else useful or funny!

**Describe alternatives you've considered**
Pinned messages in specific channels could also work, but because of Discord limitations only a certain number of messages can be pinned. Also other methods could end up causing problems if a user deletes the message or their account.

**Additional context**
React to this issue with a thumbs up to show your support and if you think this is really a feature you would enjoy!

**Comment by Zaph-x** [comment]
I'll grab this one

**Comment by zmontgo** [comment]
I’ve made this module for Finriq. I’ll link the relevant files for reference.
* Event Action: https://github.com/The-Bookery/finriq/blob/master/eventActions/starboardActions.js
* Table: https://github.com/The-Bookery/finriq/blob/master/databaseFiles/starTable.js
* Message Reaction Add: https://github.com/The-Bookery/finriq/blob/master/events/messageReactionAdd.js
* Message Reaction Remove: https://github.com/The-Bookery/finriq/blob/master/events/messageReactionRemove.js 
* Message Delete: https://github.com/The-Bookery/finriq/blob/master/events/messageDelete.js
I think that’s all the relevant files. If someone’s not working on this I’d be happy to copy/paste and test then create a PR.
